/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f446xx.h"

#define GPIOAEN			(1U<<0)
#define GPIOCEN			(1U<<2)



#define PIN5			(1U<<5)
#define PIN13			(1U<<13)

#define LED_PIN			PIN5
#define BTN_PIN			PIN13



int main(void)
{

	/*Enable clock access to GPIOA and GPIOC*/
	RCC->AHB1ENR |=GPIOAEN;
	RCC->AHB1ENR |=GPIOCEN;

    /*Set PA5 as output pin*/
	GPIOA->MODER |=(1U<<10);
	GPIOA->MODER &=~(1U<<11);

	/*Set PC13 as input pin*/
	GPIOC->MODER &=~(1U<<26);
	GPIOC->MODER &=~(1U<<27);


	while(1)
	{

		/*Check if BTN is pressed*/
		if((GPIOC->IDR & BTN_PIN) == 0)
		{
			/*Turn on led*/
		GPIOA->BSRR = LED_PIN;
		}
		else{
			/*Turn off led*/
		GPIOA->BSRR = (1U<<21);
		}

	}
}
